Traceback (most recent call last):
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.13/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import ipywidgets as widgets
from IPython.display import display
import py3Dmol

master_tabs = widgets.Tab()

tabs = []
for h,set in enumerate(data):
    set_tab = widgets.Tab()
    set_tab.children = [widgets.VBox() for system in data[set]]
    for i,system in enumerate(data[set]):
        set_tab.set_title(i, str(system))

        mols_tab = widgets.Tab()
        mols_tab.children = [widgets.VBox() for specie in data[set][system]["Species"]]
        childrens = []
        for j,specie in enumerate(data[set][system]["Species"]):
            url = "url:https://raw.githubusercontent.com/felipelewyee/DietGMTKN55-NOF/refs/heads/main/fig/{}/{}-{}.xyz".format(set_name, set, specie) 
            viewer = py3Dmol.view(url, width=400, height=300)
            viewer.setStyle({'stick': {'radius': .1}, 'sphere': {'scale': 0.25}})
            viewer.zoomTo()
            childrens.append(widgets.Output()) 
            with childrens[-1]:r
                viewer.show()
        mols_tab.children = childrens
        for j,specie in enumerate(data[set][system]["Species"]):
            mols_tab.set_title(j, str(specie))

        set_tab.children[i].children = [mols_tab]
    tabs.append(set_tab)

master_tabs.children = tabs
for i,set in enumerate(data):
    master_tabs.set_title(i, str(set))

display(master_tabs)

------------------


[0;36m  Cell [0;32mIn[5], line 24[0;36m[0m
[0;31m    viewer.show()[0m
[0m    ^[0m
[0;31mIndentationError[0m[0;31m:[0m unexpected indent


