Traceback (most recent call last):
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.13/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from bokeh.models import ColumnDataSource, FactorRange
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource, HoverTool, TapTool
import math
from bokeh.transform import factor_cmap
from bokeh.palettes import Category10

nof = "GNOF"
file = open('{}-{}-{}.yaml'.format(set_name,nof,ncwo), 'r')
data = yaml.safe_load(file)
subsets = get_Sets(data)
description = get_Descriptions(subsets)

nofs = ["PNOF5", "PNOF7s", "PNOF7", "GNOF", "GNOFm"]

data = {'subsets' : subsets}
for nof in nofs:
    if nof=="":
        file = open('{}-{}-{}.yaml'.format(set_name,"",ncwo), 'r')
    else:
        file = open('{}-{}-{}.yaml'.format(set_name,nof,ncwo), 'r')
    yaml_data = yaml.safe_load(file)
    counts = get_MADs(yaml_data)
    data[nof] = counts

descriptions = {'subsets' : subsets,
        'PNOF5'   : description,
        'PNOF7s'  : description,
        'PNOF7'   : description,
        'GNOF'    : description,
        'GNOFm'   : description}

x = [ (subset, nof) for subset in subsets for nof in nofs ]
counts = sum(zip(data['PNOF5'], data['PNOF7s'], data['PNOF7'], data['GNOF'], data['GNOFm']), ()) # like an hstack
descriptions = sum(zip(descriptions['PNOF5'], descriptions['PNOF7s'], descriptions['PNOF7'], descriptions['GNOF'], descriptions['GNOFm']), ()) # like an hstack

source = ColumnDataSource(data=dict(x=x, counts=counts, descriptions=descriptions, nofs=[f for _,f in x]))

p = figure(x_range=FactorRange(*x), width=1050, height=400, toolbar_location="left", title="150 Perfect Pairing")

p.vbar(x='x', top='counts', width=0.9, source=source, line_color="white", legend_field="nofs",
       fill_color=factor_cmap('x', palette=Category10[len(nofs)], factors=nofs, start=1, end=2))

p.y_range.start = 0
p.y_range.end = 50
p.xaxis.major_label_text_font_size = "0pt"
#p.xaxis.major_label_orientation = math.pi/2
p.xaxis.group_label_orientation = math.pi/2
p.xaxis.axis_label = "Sets"
p.yaxis.axis_label = "MAD (kcal/mol)"
p.xgrid.grid_line_color = None

p.legend.location = "top_left"
p.legend.orientation = "horizontal"

hover = HoverTool(tooltips=[
    ("Description", "@descriptions"),
    ("MAD", "@counts"),
])
p.add_tools(hover)

show(p)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[4], line 9[0m
[1;32m      6[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mbokeh[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpalettes[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m Category10
[1;32m      8[0m nof [38;5;241m=[39m [38;5;124m"[39m[38;5;124mGNOF[39m[38;5;124m"[39m
[0;32m----> 9[0m file [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[38;5;124;43m'[39;49m[38;5;132;43;01m{}[39;49;00m[38;5;124;43m-[39;49m[38;5;132;43;01m{}[39;49;00m[38;5;124;43m-[39;49m[38;5;132;43;01m{}[39;49;00m[38;5;124;43m.yaml[39;49m[38;5;124;43m'[39;49m[38;5;241;43m.[39;49m[43mformat[49m[43m([49m[43mset_name[49m[43m,[49m[43mnof[49m[43m,[49m[43mncwo[49m[43m)[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m     10[0m data [38;5;241m=[39m yaml[38;5;241m.[39msafe_load(file)
[1;32m     11[0m subsets [38;5;241m=[39m get_Sets(data)

File [0;32m~/anaconda3/envs/jb/lib/python3.13/site-packages/IPython/core/interactiveshell.py:324[0m, in [0;36m_modified_open[0;34m(file, *args, **kwargs)[0m
[1;32m    317[0m [38;5;28;01mif[39;00m file [38;5;129;01min[39;00m {[38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m2[39m}:
[1;32m    318[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    319[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mIPython won[39m[38;5;124m'[39m[38;5;124mt let you open fd=[39m[38;5;132;01m{[39;00mfile[38;5;132;01m}[39;00m[38;5;124m by default [39m[38;5;124m"[39m
[1;32m    320[0m         [38;5;124m"[39m[38;5;124mas it is likely to crash IPython. If you know what you are doing, [39m[38;5;124m"[39m
[1;32m    321[0m         [38;5;124m"[39m[38;5;124myou can use builtins[39m[38;5;124m'[39m[38;5;124m open.[39m[38;5;124m"[39m
[1;32m    322[0m     )
[0;32m--> 324[0m [38;5;28;01mreturn[39;00m [43mio_open[49m[43m([49m[43mfile[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '150-GNOF-ncwo1.yaml'

